# Site settings
title: Celtan Steven's CV 
description: Celtan Steven's CV
favicon: /assets/img/IMG_20160716_174757.jpg
baseurl: https://scspmsas.github.io/resume/
url: https://scspmsas.github.io/resume/
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Celtan Steven
  title: C#, ASP .NET MVC Developer
  address: Paris, France
  email: scspmsas@gmail.com
  link: http://scspmsas.com
  weibo:
  github: scspmsas
  linkedin: steven-celtan
  twitter: SpmSas
  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow:
#  stackoverflow: 
  workHistory:
    - work1:
      company: Ausy - Client Radioprotection and Nuclear Safety Institute
      location: Sevres, Paris
      title: C#/ASP.NET MVC Developer
      started: 2013
      duration: (2013 - Present)
      description: -Translate business and functional requirements into technical designs and solutions aligned to best practices.
      description2: -Mentor and contribute to the growth of other development team members.
      description3: -Create technical architecture and documentation.
      description4: -Translate an old application ( Powerbuilder , Jaguar, C) using the following technologies and methodologies.
      description5:  Wpf 4,ASP .Net MVC 5, Dapper, Nunit , Squirrel , Sybase 16, MVVM light , Modern UI,GIT, Sqr hypervision oracle,Scrum.
    - work2:
      company: Ausy - Client Radioprotection and Nuclear Safety Institute
      location: Sevres, Paris
      title: Java Developer
      started: 2011
      duration: (2011 - 2013)
      description: -Translate business and functional requirements into technical designs and solutions aligned to best practices.
      description2: -Mentor and contribute to the growth of other development team members.
      description3: -Create technical architecture and documentation.
      description4: Struts 2, Spring, Hibernate , Sybase 16,Talend, Business Object.
    - work3:
      company: Aptus
      location: Versaille, France
      title: Developer
      started: 2010
      duration: (2010 - 2011)
      description: Client Thales. 
      description2: Development of maritime equipment simulation application.
      description3: Eclipse, GWT , SMART-GWT.
      description4: Client Sagem .
      description5: Development of a web application to collate and make available flight analysis reports.
      description6: Zend Framework.
    - work4:
      company: Eggsist
      location: Beijing, China
      title: Php Developer
      started: 2008
      duration: (2008 - 2009)
      description: Creation and implementation of an online platform for worldwide travel.
      description2: Analysis and design. 
      description3: Creation of Storyboard and Elgg modules.Import data via openDD.
      description4: Agile Methodologies. 
      environement: PHP 5.3,SVN,Elgg Framework
  educationHistory:
    - education1:
      organization: SUPINFO
      location: Paris, France
      degree: Expert in Computer and Information Systems
      major: Software Engineering
      started: 2004
      duration: (2004 - 2009)
      description: The computer engineering compose two years after the bac + 3 and entiled M.Sc1 M.Sc.2. Students will achieve the Bachlor degree with Honour (Bac+4) at the end of the fourth year (M.Sc.1).At the end of the fifth, the final year of the (M.Sc.2) course, achieve the degree Master of Science *. In France the title is Expert in Computer and Information Systems, which is recognized by the State at level I (Bac + 5, Level Engineer, Master). 
  languages:
    - language1:
      name: French
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
  programmingSkills:
    - skill1:
      name: ASP.NET MVC
      percentage: 75%
    - skill2:
      name: SQL
      percentage: 60%
    - skill3:
      name: WPF
      percentage: 80%
    - skill5:
      name: C#
      percentage: 90%
