# Site settings
title: Celtan Steven's CV 
description: scspmsas's CV
favicon: /assets/img/IMG_20160716_174757.jpg
baseurl: https://scspmsas.github.io/resume/
url: https://scspmsas.github.io/resume/
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Celtan Steven
  title: C# Developer
  address: Paris, France
  email: scspmsas@gmail.com
  link: http://scspmsas.com
  weibo:
  github: scspmsas
  linkedin: steven-celtan
  twitter: Rahfaruto
  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow:
#  stackoverflow: 
  workHistory:
    - work1:
      company: Ausy
      location: Sevres, Paris
      title: C#/ASP.NET MVC Developer
      started: 2013
      duration: (2013 - Present)
      description: Wpf ,ASP .Net MVC 5, Dapper, Nunit , Squirrel , Sybase, MVVM light , Modern UI,GIT, Sqr hypervision oracle,Scrum
    - work2:
      company: Ausy
      location: Sevres, Paris
      title: Java Developer
      started: 2011
      duration: (2011 - 2013)
      description: Struts, Spring, Hibernate , Sybase,Talend, Business Object
    - work3:
      company: Eggsist
      location: Beijing, China
      title: Php Developer
      started: 2009
      duration: (2009 - 2012)
      description: Creation and implementation of an online platform for worldwide travel. 
        Analysis and design. Elgg framework ( Social Network).Establishment of partnership with expedia.Creation of Storyboard and Elgg modules.Import data via openDD.Used JQuery.Agile Methodologies. 
  educationHistory:
    - education1:
      organization: SUPINFO
      location: Paris, France
      degree: Expert in Computer and Information Systems
      major: Software Engineering
      started: 2004
      duration: (2004 - 2009)
      description: The computer engineering compose two years after the bac + 3 and entiled M.Sc1 M.Sc.2. Students will achieve the Bachlor degree with Honour (Bac+4) at the end of the fourth year (M.Sc.1). At the end of the fifth, the final year of the (M.Sc.2) course, achieve the degree Master of Science *. In France the title is Expert in Computer and Information Systems, which is recognized by the State at level I (Bac + 5, Level Engineer, Master). 
  languages:
    - language1:
      name: French
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
  programmingSkills:
    - skill1:
      name: HTML
      percentage: 100%
    - skill2:
      name: Bootstrap
      percentage: 90%
    - skill3:
      name: JavaScript
      percentage: 30%
    - skill5:
      name: C#/ASP.NET MVC
      percentage: 90%
