# Site settings
title: Celtan Steven's CV 
description: scspmsas's CV
favicon: /assets/img/avatar.JPG
baseurl: https://scspmsas.github.io/resume/
url: https://scspmsas.github.io/resume/
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Celtan Steven
  title: C# Developer
  address: Paris, France
  email: scspmsas@gmail.com
  link: http://scspmsas.com
  weibo:
  github: scspmsas
  linkedin: steven-celtan
  twitter: Rahfaruto
  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow:
#  stackoverflow: 
  workHistory:
    - work1:
      company: Finzsoft Solutions Ltd
      location: Auckland, New Zealand
      title: Java Developer
      started: 2014
      duration: (2014 - Present)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work2:
      company: Agfa HealthCare
      location: Shanghai, China
      title: Java Developer
      started: 2012
      duration: (2012 - 2014)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work3:
      company: Eggsist
      location: Beijing, China
      title: Java Developer
      started: 2009
      duration: (2009 - 2012)
      description: Creation and implementation of an online platform for travel worldwide .Analysis and design.Choice Elgg framework ( Social Network).Establishment of partnership with expedia.Creating storyboard.Development.Creation of Elgg modules.Import data via openDD.Used JQuery.Agile Methodologies. 
  educationHistory:
    - education1:
      organization: SUPINFO
      location: Paris, France
      degree: One-year degree before postgraduate studies in computer science
      major: Software Engineering
      started: 2004
      duration: (2004 - 2009)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  languages:
    - language1:
      name: French
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
  programmingSkills:
    - skill1:
      name: HTML
      percentage: 100%
    - skill2:
      name: Bootstrap
      percentage: 90%
    - skill3:
      name: JavaScript
      percentage: 30%
    - skill5:
      name: C#/ASP.NET MVC
      percentage: 90%
